notifications:
  slack: 9livesdatazpp:ASnedOwaNFG6eXFs15Iw6dpd#travis

language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"

before_install:
  - python --version
  - virtualenv --version
  - uname -a
  - lsb_release -a
install:
  - pip --version
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - python setup.py develop
script: nosetests
